### ISSUE TITLE
read "development" label from somewhere

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-plugin-nb2workflow#38]

**Comment by dsavchenko** [comment]
So do we read it from kg? Could you propose, how it will be stored?

**Comment by volodymyrss** [comment]
Let's read it from a kg fragment, a `ttl` file stored at some URL, the URL to be specificed in plugin config.

Maybe we can use terms from https://schema.org/WebApplication which uses https://schema.org/creativeWorkStatus to describe life cycle stage. And define terms for development, production, inherited accordingly. Store this all in this `ttl`, we will ingest part of it to upsteam core ODA ontology.

**Comment by dsavchenko** [comment]
Sounds convoluted. Currently, instrument configuration is read from the kg. The only thing missed there are allowed roles…

**Comment by volodymyrss** [comment]
It's a variation of the KG integration. We can not always expose KG through SPARQL service, it already creates way too much load since it's requested in each call, and will have more of this issues. It becomes single point of failure, and this can be mitigated by embracing federated nature of the linked data principle.

What needs to be done is to change this function to query a local graph loaded from `ttl` with rdflib:

https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/a8ca0f6ba95c5a04a3d9657aaf9027a9027b24a1/dispatcher_plugin_nb2workflow/exposer.py#L14-L15

The rest, in particular query in [there](https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/a8ca0f6ba95c5a04a3d9657aaf9027a9027b24a1/dispatcher_plugin_nb2workflow/exposer.py#L32)  will remain mostly the same, except for adding a property derived from ` https://schema.org/creativeWorkStatus `.

Another advantage of changing `kg_select` implementation is that you can update it for test without inserting new entries to the "core" KG.

**Comment by dsavchenko** [comment]
Then the bot should also be changed? Currently, it writes into central kb

**Comment by volodymyrss** [comment]
> Then the bot should also be changed? Currently, it writes into central kb

I'll adapt an export from KG.
