### ISSUE TITLE
output file names should correspond to output type

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-nb2workflow#64]

**Comment by andriineronov** [comment]
I changed .tar to .png and it worked. So just the extension name was wrong, not sure where should this be changed?

**Comment by dsavchenko** [comment]
It should be changed here, in the plugin

**Comment by andriineronov** [comment]
It would be good if fits files when downloaded have .fits in them (say, sky image in Fermi does not have extension when downloaded, even though it is fits_image=ImageDataProduct.from_fits_file('image.fits')

**Comment by dsavchenko** [comment]
This issue is more complicated, than I thought, it involves some frontend-side logic in construction of the download file names. 
As far as frontend has some restrictions (e.g. it's generally not expected to have different product types in the response, like lightcurve+image), currently I emulate "list of images" response structure regardless of actual product types. 
Most of the time, the download file name will coincide with this product file name as returned by dispatcher + '.gz' (this name is constructed in the frontend) 

In case when there is only one product ("image product"), the download file name is taken from 'download_file_name' response field. 

All this can still be addressed in the dispatcher, but frontend changes to better handle different product combinations may be useful. It could also improve the presentation of results. Currently, product table has columns "Source name" for product name, "Image" with "View" buttons, which is obviously not perfect.
